/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compiladores;

/**
 *
 * @author ASUS
 */
public enum Tokens {
    coment_1,coment_2,
    id1,id2,id3,id4,id5,id6,id7,id8,id9,id10,id11,id12,id13,id14,id15,id16,id17,id18,
    id19,id20,id21,id22,id23,id24,id25,id26,
    ELLIPSIS,COLONCOLON,DOTSTAR,ADDEQ,SUBEQ,MULEQ,DIVEQ,MODEQ,XOREQ,ANDEQ,OREQ,SL,SR,
    SLEQ,EQ,NOTEQ,LTEQ,GTEQ,ANDAND,OROR,PLUSPLUS,MINUSMINUS,ARROWSTAR,
    ARROW,ASM,AUTO,BOOL,BREAK,CASE,CATCH,CHAR,CLASS,CONST,CONST_CAST,CONTINUE,
    DEFAULT,DELETE,DO,DOUBLE,DYNAMIC_CAST,ELSE,ENUM,EXPLICIT,EXPORT,EXTERN,FALSE,SREQ,
    FLOAT,FOR,FRIEND,GOTO,IF,INLINE,INT,LONG,MUTABLE,NAMESPACE,NEW,OPERATOR,PRIVATE,
    PROTECTED,PUBLIC,REGISTER,REINTERPRET_CAST,RETURN,SHORT,SIGNED,SIZEOF,STATIC,
    STATIC_CAST,STRUCT,SWITCH,TEMPLATE,THIS,THROW,TRUE,TRY,TYPEDEF,TYPEID,TYPENAME,
    UNION,UNSIGNED,USING,VIRTUAL,VOID,VOLATILE,WCHAR_T,WHILE,ident,numero,Main,Linea,ERROR,BEGIN, END
    
}
